### ISSUE TITLE
Result Page Design

### ISSUE THREAD

**Issue by ghost** [joakimljunglin/DVA232-ProjectGroup4#23]
![Skärmavbild 2021-01-11 kl  10 30 44](https://user-images.githubusercontent.com/73971813/104164401-243e7580-53f8-11eb-9832-817603ea23e1.png)

This page could do with a label at the top where it currently says "ProjectDVA". Also something about the capitalisation of the words seems off to me. I think it would look slightly better as "You scored", and then having the exercise type as "Reading" – or even "READING", not sure.

**Comment by joakimljunglin** [comment]
I completely agree on both points. I will fix the label.

Regarding the capitalisation on the exercise name; it's like this since it receives and directly uses the activity name which is sent from the previous test activity (by Intent.setExtra). The same string is used to retrieve the relevant resources (icon and color), which are also written in lower case.
The way I see it there are two solutions.

1. I do some kind of string manipulation for the received string - turning first letter/whole string to upper case.
2. I rename the resources and string extras to "Reading" and so on. Could create rippling problems, unless the renaming refactors all uses of the resources throughout the app.

I will look into it.

**Comment by ghost** [comment]
I think option 1 is best here. It should not be too hard to find a function that does this

**Comment by ghost** [comment]
I should also change the tests so that they use the string resources when passing on the exercise type. Please tag me to the PR once done and I will commit these changes as well @joakimljunglin 

Edit: on further thoughts I don't know whether this is better or not than hardcoding the value. Sending a string resource would complicate things on the result page if we were to add support for different languages. Thoughts?

The result page should probably get the name of the type from a string resource, and not print out the passed value, that way it is possible to support adding different languages.

**Comment by joakimljunglin** [comment]
Do you mean as in sending a resource (object or ID) to the result page, or the result page retrieving the resource by using the current passed value, as it currently does with color and icon?

**Comment by ghost** [comment]
> Do you mean as in sending a resource (object or ID) to the result page, or the result page retrieving the resource by using the current passed value, as it currently does with color and icon?

The latter I think. The current issue is that the printed exercise type won't change even if the language changes, so it will be in English no matter what (not that it will become a problem here, but I guess it is still worth keeping in mind).

**Comment by joakimljunglin** [comment]
#27 should resolve all points we've discussed here.
